---
# tasks file for secure

- sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  loop:
    - "net.ipv4.icmp_echo_ignore_all"
    - "net.ipv4.icmp_echo_ignore_broadcasts"

- name: disable all inbound connection.
  firewalld:
    rich_rule: rule family="ipv4" source address="0.0.0.0/0" drop
    permanent: yes
    state: enabled
    immediate: True

- name: check the cronjobs
  copy: 
    content: ALL 
    dest: /etc/cron.deny

- name: Ensure SELinux enabled
  selinux:
    policy: targeted
    state: enforcing


  #- name: make sure that ssh is stopped/disabled
  #  service: 
  #    name: sshd
  #    state: stopped
  #    enabled: False


